name: Cleanup Old Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  cleanup:
    name: Cleanup old releases
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
